#! /usr/bin/env node

require('console-ultimate/global').replace()

var args = require('minimist')(process.argv.slice(2),
{
	string:
	[
		'env',
		'key'
	]
})

var env = args.env

if (! env)
{
	console.error('--env must be present')
}

var cmd = require('command-promise')
var partial = require('lodash/partial')

var ssh = partial(cmd, 'ssh')
var scp = partial(cmd, 'scp')

var key = args.key

if (key)
{
	ssh = partial(ssh, [ '-i', key ])
	scp = partial(scp, [ '-i', key ])
}

ssh('ubuntu@ec2-52-38-31-214.us-west-2.compute.amazonaws.com', '"uptime"')
.then(console.log)
.catch(console.error)
