#! /usr/bin/env node

require('console-ultimate/global').replace()

var rootpath = require('rootpath')

var Config = require('../src/Config')
var Log = require('../src/Log')

var Symbols = require('../src/db/models/symbols/Symbols')

var db = { helpers: require('../src/db/helpers') }


var cfg = Config(rootpath(__dirname, '../cfg'))
var log = Log()
var symbols = Symbols(db, cfg, log)

var symbol = process.argv[2]

if (! symbol)
{
	console.error('no symbol')
	process.exit(1)
}

symbols.resolve(symbol, { cache: false })
.then(console.dir, console.error)
.then(() =>
{
	return symbols.quotes(symbol)
})
.then(console.dir, console.error)
