#! /usr/bin/env node

require('console-ultimate/global').replace()

var env = 'prod'

var get_env = require('./lib/get-env')

var remote_config = get_env.remote(env) /* @shortcut */
var remote = remote_config.remote

get_env.confirm(remote_config, env) /* @shortcut */
.then(() =>
{
	console.info('GO')
})
