#! /usr/bin/env node

require('console-ultimate/global').replace()

var Config = require('../src/Config')
var rootpath = require('rootpath')

var cfg = Config(rootpath(__dirname, '../cfg'))

var knex = require('knex')

var kx = knex({
	client: 'pg',
	connection: cfg.pg
})

var prec_migr = require('../db/migrations/20161011000404_portfolio-prec')

var portfolio_table_name = 'portfolio_prec'

kx.schema.hasTable(portfolio_table_name)
.then(so =>
{
	if (! so)
	{
		return prec_migr.up(kx)
	}
})
.then(() =>
{
	return kx.from(portfolio_table_name).select(kx.raw('COUNT(*)'))
	.then(it => it.count)
	.then(Boolean)
})
.then(so =>
{
	if (so)
	{
		console.info('looks like %s already has data', portfolio_table_name)
		return
	}

	return kx.raw(`INSERT INTO ${portfolio_table_name} SELECT * FROM portfolio;`)
})
.then(console.dir, console.error)
.finally(process.exit)
